---
- name: Cleanup after bootstrap
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Packages for cleanup
      ansible.builtin.include_vars:
        file: "{{ ansible_os_family }}.yml"

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Include distribution specific cleanup tasks
      ansible.builtin.include_tasks: "cleanup-{{ ansible_os_family }}.yml"
