---
- name: Bootstrap node - pt. 1
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  collections:
    - osism.commons
    - osism.services

  roles:
    - role: resolvconf
    - role: repository

- name: Bootstrap node - pt. 2
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - ansible.builtin.include_vars:
        file: "{{ ansible_os_family }}.yml"

  vars:
    ansible_python_interpreter: /usr/bin/python3

    # cleanup
    cleanup_services_extra:
      - NetworkManager
      - iscsid
      - lxcfs
      - nscd
      - ntp
    cleanup_packages_extra:
      - dosfstools
      - ntfs-3g
      - telnet

    # packages
    upgrade_packages: false

    # operator
    operator_user: dragon
    operator_group: dragon
    operator_authorized_keys:
      - "{{ lookup('file', '/home/install/.ssh/id_rsa.pub') }}"

  collections:
    - osism.commons
    - osism.services

  roles:
    - role: chrony
    - role: systohc
    - role: configfs
    - role: packages
    - role: sysctl
    - role: services
    - role: motd
    - role: hddtemp
    - role: rng
    - role: cleanup
