---
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 8
  memory: 32G
  disk: 100
  nested_virtualization: true

env:
  DEBIAN_FRONTEND: noninteractive
  HOME: "$CIRRUS_WORKING_DIR"
  PACKER_TMP_DIR: "$CIRRUS_WORKING_DIR/.packer.d"
  MINIO_ACCESS_KEY: "ENCRYPTED[f8098deaec2915ae3a557696ffea29835461bf0601d5373a422d607cf7b758e3a4eb0679dd9b5142b6448b95f37130dc]"
  MINIO_SECRET_KEY: "ENCRYPTED[7d227766e266a8d63c5e62d6a361c071032b8ed97531510172c67a858e2ab82a8d443832180069987ef8780df0e96a56]"

build_task:
  skip: "!changesInclude('.cirrus.yml', '**.{json}', 'dev/**', 'http/**', 'scripts/**')"

  install_script:
    - apt-get update
    - apt-get install -y qemu-kvm curl git software-properties-common
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    - apt-add-repository --yes --update ppa:ansible/ansible
    - apt-get install -y packer ansible
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc alias set minio https://minio.services.osism.tech $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

  validate_packer_configurations_script:
    - packer validate -syntax-only ubuntu-20.04-amd64.json

  build_ubuntu2004_amd64_script:
    - packer build ubuntu-20.04-amd64.json

  push_script: |
    if [ "$CIRRUS_BRANCH" == "main" ]; then
      ./mc cp /dev/shm/build/* minio/openstack-ironic-images
      ./mc policy set download minio/openstack-ironic-images
    fi
