---
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 8
  memory: 32G
  disk: 100
  nested_virtualization: true

env:
  DEBIAN_FRONTEND: noninteractive
  HOME: "$CIRRUS_WORKING_DIR"
  PACKER_TMP_DIR: "$CIRRUS_WORKING_DIR/.packer.d"
  MINIO_ACCESS_KEY: "ENCRYPTED[a18259a9d07b63d4f13d0f14b8989e84572728fca044c06bc3b5628c1d2dd21c8da07a2c9a053d7d83e9d6a709659a14]"
  MINIO_SECRET_KEY: "ENCRYPTED[9f4d22031c29ad86e8f3308d956dbb8dd0385d9e76f3dd433d4687d1c224305b2ffc3e620ce04e754b97dd3b740cbbb2]"

build_task:
  skip: "!changesInclude('.cirrus.yml', '**.{json}', 'dev/**', 'http/**', 'scripts/**')"

  install_script:
    - apt-get update
    - apt-get install -y qemu-kvm curl git software-properties-common
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    - apt-add-repository --yes --update ppa:ansible/ansible
    - apt-get install -y packer ansible
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc alias set minio https://minio.services.osism.tech $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

  submodules_script:
    - git submodule init
    - git submodule update

  validate_packer_configurations_script:
    - packer validate -syntax-only ubuntu-20.04-amd64-efi.json
    - packer validate -syntax-only centos-stream-8-x86_64-efi.json

  #build_centos8_amd64_efi_script:
  #  - mv http/ks.cfg-example http/ks.cfg
  #  - sed -i 's/TODO/install/g' http/ks.cfg
  #  - packer build centos-stream-8-x86_64-efi.json
  #  - mkdir -p ./images/ && mv /dev/shm/centos-stream-8-x86_64-efi* ./images/

  build_ubuntu2004_amd64_efi_script:
    - mv http/preseed.cfg-example http/preseed.cfg
    - sed -i 's/TODO/install/g' http/preseed.cfg
    - packer build ubuntu-20.04-amd64-efi.json
    - mkdir -p ./images/ && mv /dev/shm/ubuntu-20.04-amd64-efi* ./images/

  push_script: |
    if [ "$CIRRUS_BRANCH" == "main" ]; then
      ./mc cp images/* minio/openstack-ironic-images
      ./mc policy set download minio/openstack-ironic-images
    fi
