---
compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-kvm
  platform: linux
  cpu: 4
  memory: 16G
  disk: 100
  nested_virtualization: true

env:
  DEBIAN_FRONTEND: noninteractive
  HOME: "$CIRRUS_WORKING_DIR"
  PACKER_TMP_DIR: "$CIRRUS_WORKING_DIR/.packer.d"
  MINIO_ACCESS_KEY: "ENCRYPTED[8741c780eb239a6d8418328d246dd55cb3b1137f76f7e94f7c491481f833dfc426828ec413661d81bd5849067627aebd]"
  MINIO_SECRET_KEY: "ENCRYPTED[efc1800216e365a2e3d921e1c6ff85e05877c4f4eec20c1078a67a8259f5724e3863ff73209a6f0a0d9948b14913f075]"

build_task:
  skip: "!changesInclude('.cirrus.yml', '**.{json}', 'dev/**', 'http/**', 'scripts/**')"

  install_script:
    - apt-get update
    - apt-get install -y qemu-kvm curl git software-properties-common
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
    - apt-add-repository --yes --update ppa:ansible/ansible
    - apt-get install -y packer ansible
    - wget https://dl.min.io/client/mc/release/linux-amd64/mc
    - chmod +x mc
    - ./mc alias set minio https://images.osism.tech $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

  submodules_script:
    - git submodule init
    - git submodule update

  validate_packer_configurations_script:
    - packer validate -syntax-only ubuntu-20.04-amd64-efi.json
    - packer validate -syntax-only centos-stream-8-x86_64-efi.json

  # build_centos8_amd64_efi_script:
  #   - mv http/ks.cfg-example http/ks.cfg
  #   - sed -i 's/TODO/install/g' http/ks.cfg
  #   - packer build centos-stream-8-x86_64-efi.json
  #   - mkdir -p ./images/ && mv ./builds/* ./images/

  build_ubuntu2004_amd64_efi_script:
    - rm -rf ./builds/
    - mv http/preseed.cfg-example http/preseed.cfg
    - sed -i 's/TODO/install/g' http/preseed.cfg
    - packer build ubuntu-20.04-amd64-efi.json
    - mkdir -p ./images/
    - mv ubuntu-20.04-amd64-efi.gz ./images/

  push_script:
    - ./mc cp images/* minio/openstack-ironic-images
    - ./mc policy set download minio/openstack-ironic-images
